//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string MaPhieuDatPhong { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.TimeSpan> GioDat { get; set; }
        public string MaKhuyenMai { get; set; }
        public string TinhTrang { get; set; }
        public string MaKhach { get; set; }
        public string MaPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Khach Khach { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
